apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd
  labels:
    app: cdlabels
spec:
  replicas: 2
  selector: 
    matchLabels:  
      app:  nginx
  template: 
    metadata:
      labels:
        app:  nginx
    spec:
      containers: nginx-container
      image:  nginx
      containerPort:  80